# device
device: cpu

# model
random_seed: 2023
chunk_size: 50
y_col: type_label
num_labels: 7
dropout: 0.01
loss: cross
modal: t_a_v
att: t_a_v
hidden:
  t: 768
  a: 25
  v: 69
  x: 0
num_token: 150
agg_type: bilstm
hetero_type: min
rel_type: va
graphuse: True
edge_weight: True
update: True

# paths
keyword_path: /workspace/RAPID/dataset/_disfluency_tk_300.json
checkpoint_path: Your model checkpoint path
video_path: Your video path

# api
api_key: Your api key